added backend
RyanWalker277/EcoJoy pull request #12
Opened 2022-09-10 20:19 UTC by Yash-Var

2022-09-10 21:52 UTC, RyanWalker277 commented on Rakathon/views.py
> +# from contact_queries.models import User_Messages
remove this comment

2022-09-10 21:54 UTC, RyanWalker277 commented on Templates/contact.html
> +                                        <input type="text" class="form-control" name="yname" id="contact-name" placeholder="Your Name">
change name="yname" to name = "name"

2022-09-10 21:56 UTC, RyanWalker277 commented on contact_queries/urls.py
> +    # path('', views.contact_index , name = "submit_message"),
delete this comment

2022-09-10 21:57 UTC, RyanWalker277 commented on contact_queries/views.py
> +# def contact(request):
remove these comments

2022-09-10 21:58 UTC, RyanWalker277 requested changes
Kindly do the necessary changes

2022-09-10 21:59 UTC, RyanWalker277 commented on contact_queries/views.py
> +                name = request.POST.get('contact-name')
change "contact-name" to "name"

2022-09-10 22:00 UTC, RyanWalker277 commented on contact_queries/views.py
> +                email = request.POST.get('contact-email')
change "contact-email" to "email"

2022-09-10 22:00 UTC, RyanWalker277 commented on contact_queries/views.py
> +                subject = request.POST.get('contact-subject')
change "contact-subject" to "subject"

2022-09-11 05:04 UTC, Yash-Var commented
@RyanWalker277 i am closed pr make a new PR

2022-09-11 05:04 UTC, closed without merging